### ISSUE TITLE
Any way to debug/log this on Windows?

### ISSUE THREAD

**Issue by TheGoddessInari** [GabrielMajeri/d3d9-to-11#1]
As a curiosity/reference it'd be good to have this easily testable on Windows.

Setting RUST_LOG as indicated didn't produce any log output on native Windows despite the d3d9 getting loaded and the program exiting.

**Comment by GabrielMajeri** [comment]
Hmm, could you run the unit tests and see if they print any output? AppVeyor runs Windows, so this library is constantly tested with Windows and Linux. Please follow the [testing instructions](https://github.com/GabrielMajeri/d3d9-to-11/blob/master/docs/tests.md) and report back.

You should at the least see something like

```
running 1 test
test core::context::tests::context_lifetime ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

The thing is that the library is still under heavy development. The unit tests show no output for now (except when they fail). Most D3D9 applications will only show something like `d3d9::entry: D3D9 version 9.0c` in the log, since there is little functionality for now.

**Comment by TheGoddessInari** [comment]
The test passes, yes. Oh, I see it's clarified in the README now that it's not able to run real games, okay. That makes sense then.

I was mostly trying to figure out if there was some way to get appropriate logging output on actual Windows so I could see what was failing when trying it vs. an actual game.

Turns out, things are just on stderr, and for a GUI program I need to redirect like ```> debug.log 2>&1``` to see it at all. Not very convenient, but also not your bug.
