### ISSUE TITLE
A Wiki Page.

### ISSUE THREAD

**Issue by Thinkaboutmin** [GabrielMajeri/d3d9-to-11#3]
This might be silly, as the project just started... But, just as a reminder, what about a wiki using the Github feature? Although I "made", Crtl + C - Crtl + V from the docs, one in my [fork](https://github.com/Thinkaboutmin/d3d9-to-11), if it's even helpful.

**Comment by GabrielMajeri** [comment]
Hello @Thinkaboutmin, I intentionally _disabled_ the wiki because I think it is the right way to having documentation. The issue with wikis is that they either:

- only allow me, the repo owner to edit them
- they allow anyone to edit them, without allowing for any sort of review

Which is why I prefer storing all the documentation in the repo itself. That way, we can use _pull requests_ to submit changes to the documentation, and these changes can be reviewed, discussed, etc.

However, I do agree there should be an easier way of reading the docs. I planned to set up a [GitHub Pages](https://pages.github.com/) site for the docs (they are already in the right format), but I didn't have time.

**Comment by GabrielMajeri** [comment]
GitHub pages site is now live at https://gabrielmajeri.github.io/d3d9-to-11/, displaying the documentation in the docs folder in an online format.
